const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire",
  "Bosnia ",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British ",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea ",
  "Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia ",
  "Moldova ",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States Minor Outlying Islands",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela ",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

const bangladeshLocations = [
  "Bagerhat",
  "Bagerhat Sadar",
  "Chitalmari",
  "Fakirhat",
  "Kachua",
  "Mollahat",
  "Mongla",
  "Morrelganj",
  "Rampal",
  "Sarankhola",
  "Bandarban",
  "Bandarban Sadar",
  "Lama",
  "Naikhongchhari",
  "Rowangchhari",
  "Ruma",
  "Thanchi",
  "Barguna",
  "Amtali",
  "Bamna",
  "Barguna Sadar",
  "Betagi",
  "Patharghata",
  "Barisal",
  "Agailjhara",
  "Babuganj",
  "Bakerganj",
  "Banaripara",
  "Gaurnadi",
  "Hizla",
  "Mehendiganj",
  "Muladi",
  "Barisal Sadar",
  "Bhola",
  "Bhola Sadar",
  "Burhanuddin",
  "Char Fasson",
  "Daulatkhan",
  "Lalmohan",
  "Manpura",
  "Tazumuddin",
  "Bogra",
  "Adamdighi",
  "Bogra Sadar",
  "Dhunat",
  "Dhupchanchia",
  "Gabtali",
  "Kahaloo",
  "Nandigram",
  "Sariakandi",
  "Shajahanpur",
  "Sherpur",
  "Shibganj",
  "Brahmanbaria",
  "Ashuganj",
  "Bancharampur",
  "Bijoynagar",
  "Brahmanbaria Sadar",
  "Kasba",
  "Nabinagar",
  "Nasirnagar",
  "Sarail",
  "Chandpur",
  "Chandpur Sadar",
  "Faridganj",
  "Haimchar",
  "Haziganj",
  "Kachua",
  "Matlab Dakshin",
  "Matlab Uttar",
  "Shahrasti",
  "Chapai Nawabganj",
  "Bholahat",
  "Gomastapur",
  "Nachole",
  "Nawabganj Sadar",
  "Shibganj",
  "Chattogram",
  "Anwara",
  "Banshkhali",
  "Boalkhali",
  "Chandanaish",
  "Fatikchhari",
  "Hathazari",
  "Lohagara",
  "Mirsharai",
  "Patiya",
  "Rangunia",
  "Raozan",
  "Sandwip",
  "Satkania",
  "Sitakunda",
  "Chattogram Sadar",
  "Chuadanga",
  "Alamdanga",
  "Chuadanga Sadar",
  "Damurhuda",
  "Jibannagar",
  "Cox's Bazar",
  "Chakaria",
  "Cox's Bazar Sadar",
  "Kutubdia",
  "Maheshkhali",
  "Pekua",
  "Ramu",
  "Teknaf",
  "Ukhia",
  "Cumilla",
  "Barura",
  "Brahmanpara",
  "Burichang",
  "Chandina",
  "Chauddagram",
  "Cumilla Adarsha Sadar",
  "Cumilla Sadar Dakshin",
  "Daudkandi",
  "Debidwar",
  "Homna",
  "Laksam",
  "Meghna",
  "Monohorgonj",
  "Muradnagar",
  "Nangalkot",
  "Titas",
  "Dhaka",
  "Dhamrai",
  "Dohar",
  "Keraniganj",
  "Nawabganj",
  "Savar",
  "Dinajpur",
  "Birampur",
  "Birganj",
  "Biral",
  "Bochaganj",
  "Chirirbandar",
  "Dinajpur Sadar",
  "Fulbari",
  "Ghoraghat",
  "Hakimpur",
  "Kaharole",
  "Khansama",
  "Nawabganj",
  "Faridpur",
  "Alfadanga",
  "Bhanga",
  "Boalmari",
  "Charbhadrasan",
  "Faridpur Sadar",
  "Madhukhali",
  "Nagarkanda",
  "Sadarpur",
  "Saltha",
  "Feni",
  "Chhagalnaiya",
  "Daganbhuiyan",
  "Feni Sadar",
  "Parshuram",
  "Sonagazi",
  "Gaibandha",
  "Fulchhari",
  "Gaibandha Sadar",
  "Gobindaganj",
  "Palashbari",
  "Sadullapur",
  "Saghata",
  "Sundarganj",
  "Gazipur",
  "Gazipur Sadar",
  "Kaliakair",
  "Kaliganj",
  "Kapasia",
  "Sreepur",
  "Gopalganj",
  "Gopalganj Sadar",
  "Kashiani",
  "Kotalipara",
  "Muksudpur",
  "Tungipara",
  "Habiganj",
  "Ajmiriganj",
  "Bahubal",
  "Baniachang",
  "Chunarughat",
  "Habiganj Sadar",
  "Lakhai",
  "Madhabpur",
  "Nabiganj",
  "Jamalpur",
  "Bakshiganj",
  "Dewanganj",
  "Islampur",
  "Jamalpur Sadar",
  "Madarganj",
  "Melandaha",
  "Sarishabari",
  "Jashore",
  "Abhaynagar",
  "Bagherpara",
  "Chaugachha",
  "Jhikargacha",
  "Keshabpur",
  "Manirampur",
  "Sharsha",
  "Jashore Sadar",
  "Jhalokati",
  "Jhalokati Sadar",
  "Kathalia",
  "Nalchity",
  "Rajapur",
  "Jhenaidah",
  "Harinakunda",
  "Jhenaidah Sadar",
  "Kaliganj",
  "Kotchandpur",
  "Maheshpur",
  "Shailkupa",
  "Joypurhat",
  "Akkelpur",
  "Joypurhat Sadar",
  "Kalai",
  "Khetlal",
  "Panchbibi",
  "Khagrachari",
  "Dighinala",
  "Khagrachari Sadar",
  "Laxmichhari",
  "Mahalchhari",
  "Manikchhari",
  "Matiranga",
  "Panchhari",
  "Ramgarh",
  "Khulna",
  "Batiaghata",
  "Dacope",
  "Dumuria",
  "Dighalia",
  "Koyra",
  "Paikgachha",
  "Phultala",
  "Rupsa",
  "Terokhada",
  "Khulna Sadar",
  "Kishoreganj",
  "Austagram",
  "Bajitpur",
  "Bhairab",
  "Hossainpur",
  "Itna",
  "Karimganj",
  "Katiadi",
  "Kishoreganj Sadar",
  "Kuliarchar",
  "Mithamain",
  "Nikli",
  "Pakundia",
  "Tarail",
  "Kurigram",
  "Bhurungamari",
  "Char Rajibpur",
  "Chilmari",
  "Kurigram Sadar",
  "Nageshwari",
  "Phulbari",
  "Rajarhat",
  "Raomari",
  "Ulipur",
  "Kushtia",
  "Bheramara",
  "Daulatpur",
  "Khoksa",
  "Kumarkhali",
  "Kushtia Sadar",
  "Mirpur",
  "Lakshmipur",
  "Kamalnagar",
  "Lakshmipur Sadar",
  "Ramganj",
  "Ramgati",
  "Raipur",
  "Lalmonirhat",
  "Aditmari",
  "Hatibandha",
  "Kaliganj",
  "Lalmonirhat Sadar",
  "Patgram",
  "Madaripur",
  "Kalkini",
  "Madaripur Sadar",
  "Rajoir",
  "Shibchar",
  "Magura",
  "Magura Sadar",
  "Mohammadpur",
  "Shalikha",
  "Sreepur",
  "Manikganj",
  "Daulatpur",
  "Ghior",
  "Harirampur",
  "Manikganj Sadar",
  "Saturia",
  "Shibalaya",
  "Singair",
  "Meherpur",
  "Gangni",
  "Meherpur Sadar",
  "Mujibnagar",
  "Moulvibazar",
  "Barlekha",
  "Juri",
  "Kamalganj",
  "Kulaura",
  "Moulvibazar Sadar",
  "Rajnagar",
  "Sreemangal",
  "Munshiganj",
  "Gazaria",
  "Lohajang",
  "Munshiganj Sadar",
  "Sirajdikhan",
  "Sreenagar",
  "Tongibari",
  "Mymensingh",
  "Bhaluka",
  "Dhobaura",
  "Fulbaria",
  "Gaffargaon",
  "Gauripur",
  "Haluaghat",
  "Ishwarganj",
  "Muktagachha",
  "Mymensingh Sadar",
  "Nandail",
  "Phulpur",
  "Naogaon",
  "Atrai",
  "Badalgachhi",
  "Dhamoirhat",
  "Manda",
  "Mohadevpur",
  "Naogaon Sadar",
  "Niamatpur",
];

let perpard = [...bangladeshLocations, ...countryList];
